#!/sbin/openrc-run

description="LXMF Router Daemon"

command="/opt/reticulum/bin/lxmd"
command_args="--service --config /var/lib/reticulum/lxmd --rnsconfig /etc/reticulum"
command_user="reticulum:reticulum"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"

depend() {
    need net rnsd
}

start_pre() {
    checkpath --directory --owner reticulum:reticulum --mode 0755 /etc/reticulum/storage
}
